services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_container
    restart: unless-stopped
    command: gunicorn -b 0.0.0.0:8000 django_docker.wsgi:application"
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
#    ports:
#      - "8000:8000"
    environment:
      DEBUG: "False"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static:/app/static
      - media:/app/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static:
  media: