services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_container
    restart: unless-stopped
    command: gunicorn -c gunicorn_conf.py django_docker.wsgi:application
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
    networks:
      - mynetwork

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./nginx/nginx.conf:/app/nginx/nginx.conf
      - static:/app/static
      - media:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  static:
  media: